/*
 * Copyright (c) 2026 Jorge Guzman
 * SPDX-License-Identifier: Apache-2.0
 */

#ifndef SOC_RISCV_GIGADEVICE_GD32VW55X_GD32_REGS_H_
#define SOC_RISCV_GIGADEVICE_GD32VW55X_GD32_REGS_H_

#include <zephyr/sys/util_macro.h>

/* RCU */
#define RCU_CFG0_OFFSET      0x08U
#define RCU_AHB1EN_OFFSET    0x30U
#define RCU_AHB2EN_OFFSET    0x34U
#define RCU_AHB3EN_OFFSET    0x38U
#define RCU_APB1EN_OFFSET    0x40U
#define RCU_APB2EN_OFFSET    0x44U
#define RCU_CFG1_OFFSET      0x8CU

#define RCU_CFG0_AHBPSC_POS  4U
#define RCU_CFG0_AHBPSC_MSK  (BIT_MASK(4) << RCU_CFG0_AHBPSC_POS)
#define RCU_CFG0_APB1PSC_POS 10U
#define RCU_CFG0_APB1PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB1PSC_POS)
#define RCU_CFG0_APB2PSC_POS 13U
#define RCU_CFG0_APB2PSC_MSK (BIT_MASK(3) << RCU_CFG0_APB2PSC_POS)

/* EFUSE product UID (PUID0..PUID2) */
#define GD32_UID_BASE         0x40022854U
#define GD32_UID_WORD0        (GD32_UID_BASE + 0x0U)
#define GD32_UID_WORD1        (GD32_UID_BASE + 0x4U)
#define GD32_UID_WORD2        (GD32_UID_BASE + 0x8U)

#define RCU_RSTSCK_OFFSET    0x74U
#define RCU_RSTSCK_RSTFC     BIT(24)
#define RCU_RSTSCK_EPRSTF    BIT(26)
#define RCU_RSTSCK_PORRSTF   BIT(27)
#define RCU_RSTSCK_SWRSTF    BIT(28)
#define RCU_RSTSCK_FWDGTRSTF BIT(29)
#define RCU_RSTSCK_WWDGTRSTF BIT(30)
#define RCU_RSTSCK_LPRSTF    BIT(31)

#endif /* SOC_RISCV_GIGADEVICE_GD32VW55X_GD32_REGS_H_ */
